//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp15
{
    using System;
    using System.Collections.Generic;
    
    public partial class T1
    {
        public int id_ { get; set; }
        public int id_name { get; set; }
        public string dat { get; set; }
        public string cot { get; set; }
    
        public virtual T2 T2 { get; set; }
    }
}
